### ISSUE TITLE
[2.0] Quoting value system doesn't work well with QUOTE_PARTIALLY option

### ISSUE THREAD

**Issue by aetiom** [bulton-fr/bfw-sql#41]
SqlAction::quoteValue()

```php
        /**
         * If the status allow to quote partially, check if the column is
         * not declared to be quoted or is declared to be not quote.
         */
        if (
            (
                !isset($this->quotedColumns[$columnName])
                || isset($this->notQuotedColumns[$columnName])
            )
            && $this->quoteStatus === self::QUOTE_PARTIALLY
        ) {
            return $value;
        }
```

This action require user to provide quotedColumns AND notQuotedColums.
Pretty embarassing for people who have very large tables

**Comment by bulton-fr** [comment]
Example : 
Table with 20 columns.
One column should not be automatic quoted, but the rest should be.
It is currently necessary to declare what remains (19 columns) as quoted

**Comment by bulton-fr** [comment]
Note:

PartialMode | into quotedColumns | into notQuotedColumns | Result
------------|--------------------|-----------------------|-------
quoted | 0 | 0 | quote
quoted | 0 | 1 | not quote
quoted | 1 | 0 | quote
quoted | 1 | 1 | Exception
notQuoted | 0 | 0 | not quote
notQuoted | 0 | 1 | not quote
notQuoted | 1 | 0 | quote
notQuoted | 1 | 1 | Exception
